name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Trigger Site Rebuild
    steps:
      - name: cURL request
        run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK }}
